from Database.db_settings import execute_query


def add_info_to_table():
    add_states_for_states_table ='''
INSERT INTO states (name) VALUES
('Tashkent City'),
('Andijan Region'),
('Bukhara Region'),
('Fergana Region'),
('Jizzakh Region'),
('Kashkadarya Region'),
('Navoi Region'),
('Namangan Region'),
('Samarkand Region'),
('Syrdarya Region'),
('Surkhandarya Region'),
('Khorezm Region'),
('Karakalpakstan'),
('Tashkent Region')
ON CONFLICT (name) DO NOTHING;
'''


    add_info_for_regions_table = '''
INSERT INTO regions (name, state_id) VALUES
('Yunusabad District', 1),
('Yashnabad District', 1),
('Chilanzar District', 1),
('Mirzo-Ulugbek District', 1),
('Shaykhontohur District', 1),
('Almazar District', 1),
('Mirobod District', 1),
('Sergeli District', 1),
('Hamza District', 1),
('Bektemir District', 1),
('Andijan', 2),
('Asaka', 2),
('Baliqchi', 2),
('Boz', 2),
('Izboskan', 2),
('Jalal-Abad', 2),
('Khanabad', 2),
('Marhamat', 2),
('Oltinkul', 2),
('Shahrihon', 2),
('Ulugnor', 2),
('Bukhara', 3),
('Gijduvan', 3),
('Jondor', 3),
('Karakul', 3),
('Kogon', 3),
('Shafirkan', 3),
('Vobkent', 3),
('Fergana', 4),
('Andijan', 4),
('Margilan', 4),
('Rishtan', 4),
('Kuva', 4),
('Oltiariq', 4),
('Uchquduq', 4),
('Jizzakh', 5),
('Arnasay', 5),
('Bakhmal', 5),
('Dustlik', 5),
('Forish', 5),
('Mirzachul', 5),
('Zafarabad', 5),
('Karshi', 6),
('Chirakchi', 6),
('Guzar', 6),
('Kitab', 6),
('Muborak', 6),
('Shahrisabz', 6),
('Yakkabag', 6),
('Navoi', 7),
('Karman', 7),
('Nurota', 7),
('Uchkuduk', 7),
('Zafarabad', 7),
('Konimex', 7),
('Namangan', 8),
('Chortoq', 8),
('Kosonsoy', 8),
('Pap', 8),
('Chust', 8),
('Mingbulak', 8),
('Samarkand', 9),
('Kattakurgan', 9),
('Nurabad', 9),
('Oqdarya', 9),
('Payariq', 9),
('Pastdargom', 9),
('Gulistan', 10),
('Syrdarya', 10),
('Khavast', 10),
('Mirzaabad', 10),
('Saykhunabad', 10),
('Yangiyer', 10),
('Termez', 11),
('Sherabad', 11),
('Boysun', 11),
('Angor', 11),
('Jarkurgan', 11),
('Muzrobod', 11),
('Shargun', 11),
('Urgench', 12),
('Khiva', 12),
('Beruni', 12),
('Gurlan', 12),
('Shavat', 12),
('Nukus', 13),
('Karauzyak', 13),
('Shumanay', 13),
('Takhtakupir', 13),
('Beruni', 13),
('Khodzhaeli', 13),
('Akhangaran', 14),
('Bekabad', 14),
('Chinaz', 14),
('Kibray', 14),
('Namangan', 14),
('Ohangaron', 14),
('Pskent', 14),
('Tashkent District', 14),
('Yangiyul', 14),
('Yangibozor', 14)
ON CONFLICT (name, state_id) DO NOTHING;'''


    execute_query(add_states_for_states_table)
    execute_query(add_info_for_regions_table)